=== gadgetmies/flow-recipe/packages/server/src/recipes/recipe.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    
    <!-- Root element: recipe -->
    <xs:element name="recipe">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="title" type="xs:string"/>
                <xs:element name="ingredients">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ingredient" maxOccurs="unbounded">
                                <xs:complexType mixed="true">
                                    <xs:sequence>
                                        <xs:element name="properties" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="property" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:choice>
                                                                <xs:element name="numeric-value" type="numeric-value-type"/>
                                                                <xs:element name="text-content" type="xs:string" minOccurs="0"/>
                                                            </xs:choice>
                                                            <xs:attribute name="name" type="xs:string" use="required"/>
                                                            <xs:attribute name="value" type="xs:string"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="tools">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="tool" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType mixed="true">
                                    <xs:sequence>
                                        <xs:element name="properties" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="property" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:choice>
                                                                <xs:element name="numeric-value" type="numeric-value-type"/>
                                                                <xs:element name="text-content" type="xs:string" minOccurs="0"/>
                                                            </xs:choice>
                                                            <xs:attribute name="name" type="xs:string" use="required"/>
                                                            <xs:attribute name="value" type="xs:string"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="tasks">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="task" maxOccurs="unbounded">
                                <xs:complexType mixed="true">
                                    <xs:choice maxOccurs="unbounded">
                                        <xs:element name="input">
                                            <xs:complexType mixed="true">
                                                <xs:attribute name="ref" type="xs:string" use="required"/>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="tool">
                                            <xs:complexType mixed="true">
                                                <xs:attribute name="ref" type="xs:string" use="required"/>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="output">
                                            <xs:complexType mixed="true">
                                                <xs:attribute name="id" type="xs:string" use="required"/>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="options">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="option" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:choice>
                                                                <xs:element name="numeric-value" type="numeric-value-type"/>
                                                                <xs:element name="text-content" type="xs:string" minOccurs="0"/>
                                                            </xs:choice>
                                                            <xs:attribute name="name" type="xs:string" use="required"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="tools">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="tool" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:attribute name="ref" type="xs:string" use="required"/>
                                                            <xs:attribute name="reserved" type="xs:boolean"/>
                                                            <xs:attribute name="name" type="xs:string"/>
                                                            <xs:attribute name="reusable" type="xs:boolean"/>
                                                            <xs:attribute name="amount" type="xs:decimal" default="1"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="inputs">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="input" maxOccurs="unbounded">
                                                        <xs:complexType mixed="true">
                                                            <xs:attribute name="ref" type="xs:string" use="required"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="outputs">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:choice maxOccurs="unbounded">
                                                        <xs:element name="output">
                                                            <xs:complexType>
                                                                <xs:simpleContent>
                                                                    <xs:extension base="xs:string">
                                                                        <xs:attribute name="id" type="xs:string" use="required"/>
                                                                    </xs:extension>
                                                                </xs:simpleContent>
                                                            </xs:complexType>
                                                        </xs:element>
                                                        <xs:element name="tool">
                                                            <xs:complexType>
                                                                <xs:attribute name="ref" type="xs:string" use="required"/>
                                                                <xs:attribute name="name" type="xs:string"/>
                                                                <xs:attribute name="reusable" type="xs:boolean"/>
                                                                <xs:attribute name="amount" type="xs:decimal" default="1"/>
                                                            </xs:complexType>
                                                        </xs:element>
                                                    </xs:choice>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="instructions">
                                            <xs:complexType mixed="true">
                                                <xs:choice maxOccurs="unbounded">
                                                    <xs:element name="input">
                                                        <xs:complexType mixed="true">
                                                            <xs:attribute name="ref" type="xs:string" use="required"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="tool">
                                                        <xs:complexType mixed="true">
                                                            <xs:attribute name="ref" type="xs:string" use="required"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="output">
                                                        <xs:complexType mixed="true">
                                                            <xs:attribute name="id" type="xs:string" use="required"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="option">
                                                        <xs:complexType>
                                                            <xs:choice>
                                                                <xs:element name="numeric-value" type="numeric-value-type"/>
                                                                <xs:element name="text-content" type="xs:string" minOccurs="0"/>
                                                            </xs:choice>
                                                            <xs:attribute name="name" type="xs:string" use="required"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:choice>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:choice>
                                    <xs:attribute name="operation" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="ref" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    
    <!-- Numeric value type -->
    <xs:complexType name="numeric-value-type">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="number" type="xs:decimal" use="required"/>
                <xs:attribute name="unit" type="xs:string"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    
</xs:schema>

=== gadgetmies/flow-recipe/packages/server/src/recipes/tiramisu.xml
<?xml version="1.0" encoding="utf-8"?>
<recipe xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="recipe.xsd">
    <title>Simplified Tiramisu (using ready-made ingredients)</title>
    <ingredients>
        <ingredient id="ladyfingers">ladyfingers</ingredient>
        <ingredient id="coffee">strong coffee or espresso</ingredient>
        <ingredient id="mascarpone">mascarpone</ingredient>
        <ingredient id="whipped-cream">whipped cream</ingredient>
        <ingredient id="sugar">sugar</ingredient>
        <ingredient id="vanilla-extract">vanilla extract</ingredient>
        <ingredient id="cocoa-powder">cocoa powder</ingredient>
    </ingredients>
    <tools>
        <tool id="mixing-bowl">bowl</tool>
        <tool id="spoon">spoon</tool>
        <tool id="shallow-dish">shallow dish</tool>
        <tool id="cup">cup</tool>
        <tool id="square-dish">square dish</tool>
        <tool id="cover">cover</tool>
        <tool id="kitchen-scale">kitchen scale</tool>
        <tool id="flour-sieve">flour sieve</tool>
        <tool id="plate">plate</tool>
    </tools>
    <tasks>
        <task operation="measure">
            <options>
                <option name="amount">
                    <numeric-value number="250" unit="g" />
                </option>
            </options>
            <tools>
                <tool ref="mixing-bowl" reusable="true" />
                <tool ref="kitchen-scale" reusable="true" />
            </tools>
            <inputs>
                <input ref="mascarpone" />
            </inputs>
            <outputs>
                <output id="measured-mascarpone">mascarpone</output>
            </outputs>
        </task>
        <task operation="measure">
            <options>
                <option name="amount">
                    <numeric-value number="30" unit="g">converted from volume</numeric-value>
                </option>
            </options>
            <tools>
                <tool ref="mixing-bowl" reusable="true" />
                <tool ref="kitchen-scale" reusable="true" />
            </tools>
            <inputs>
                <input ref="sugar" />
            </inputs>
            <outputs>
                <output id="measured-sugar">sugar</output>
            </outputs>
        </task>
        <task operation="measure">
            <options>
                <option name="amount">
                    <numeric-value number="1" unit="tsp" />
                </option>
            </options>
            <tools>
                <tool ref="cup" reusable="true" />
            </tools>
            <inputs>
                <input ref="vanilla-extract" />
            </inputs>
            <outputs>
                <output id="measured-vanilla">vanilla extract</output>
            </outputs>
        </task>
        <task operation="measure">
            <options>
                <option name="amount">
                    <numeric-value number="250" unit="ml">converted from 2 cups</numeric-value>
                </option>
            </options>
            <tools>
                <tool ref="mixing-bowl" reserved="true" reusable="true" />
            </tools>
            <inputs>
                <input ref="coffee" />
            </inputs>
            <outputs>
                <output id="measured-coffee">coffee</output>
            </outputs>
        </task>
        <task operation="mix">
            <tools>
                <tool ref="spoon" reusable="true" />
                <tool ref="mixing-bowl" reserved="true" reusable="true" />
            </tools>
            <inputs>
                <input ref="measured-mascarpone" />
                <input ref="measured-sugar" />
                <input ref="measured-vanilla" />
            </inputs>
            <outputs>
                <output id="cream-base">cream base</output>
            </outputs>
        </task>
        <task operation="fold">
            <tools>
                <tool ref="mixing-bowl" reserved="true" reusable="true" />
                <tool ref="spoon" reusable="true" />
            </tools>
            <inputs>
                <input ref="cream-base" />
                <input ref="whipped-cream" />
            </inputs>
            <outputs>
                <output id="cream-mixture">cream mixture</output>
            </outputs>
        </task>
        <task operation="pour">
            <tools>
                <tool ref="shallow-dish" reusable="true" />
            </tools>
            <inputs>
                <input ref="measured-coffee" />
            </inputs>
            <outputs>
                <output id="coffee-in-dish">coffee dish</output>
            </outputs>
        </task>
        <task operation="soak">
            <options>
                <option name="duration">
                    <numeric-value number="5" unit="seconds" />
                </option>
            </options>
            <instructions><!--
                TODO: how to indicate the plate is the same plate? -->
            Take a <tool ref="plate" />. Soak <input ref="ladyfingers" amount="10" /> in the <input
                    ref="coffee-in-dish" /> for 5 seconds and place them on the <tool ref="plate" />
            . </instructions>
            <outputs>
                <output id="dipped-ladyfingers-layer">dipped ladyfingers</output>
            </outputs>
        </task>
        <task operation="place">
            <tools>
                <tool ref="square-dish" reusable="true" />
            </tools>
            <inputs>
                <input ref="dipped-ladyfingers-layer" />
            </inputs>
            <outputs>
                <output id="first-ladyfinger-layer">layer of ladyfingers</output>
            </outputs>
        </task>
        <task operation="spread">
            <tools>
                <tool ref="spoon" reusable="true" />
            </tools>
            <inputs>
                <input ref="cream-mixture" />
                <input ref="first-ladyfinger-layer" />
            </inputs>
            <outputs>
                <output id="layer-with-cream">cream layer</output>
            </outputs>
        </task>
        <task operation="dust">
            <inputs>
                <input ref="layer-with-cream" />
                <input ref="cocoa-powder" />
            </inputs>
            <tools>
                <tool ref="flour-sieve" />
            </tools>
            <outputs>
                <output id="dusted-tiramisu">dusted tiramisu</output>
            </outputs>
        </task>
    </tasks>
</recipe>

=== gadgetmies/flow-recipe/packages/server/src/recipes/sandwich.xml
<?xml version="1.0" encoding="utf-8" ?>
<recipe xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="recipe.xsd">
    <title>Simple Butter Sandwich</title>
    <ingredients>
        <ingredient id="bread">bread</ingredient>
        <ingredient id="butter">butter</ingredient>
        <ingredient id="cucumber">cucumber</ingredient>
        <ingredient id="tomato">tomato</ingredient>
    </ingredients>
    <tools>
        <tool id="knife">knife</tool>
        <tool id="plate">plate</tool>
    </tools>
    <tasks>
        <task operation="split">
            <options>
                <option name="parts">
                    <numeric-value number="2"/>
                </option>
            </options>
            <inputs>
                <input ref="bread"/>
            </inputs>
            <tools>
                <tool ref="knife" reusable="true"/>
            </tools>
            <outputs>
                <output id="bread-slice">bread slices</output>
            </outputs>
        </task>
        <task operation="spread">
            <inputs>
                <input ref="butter"/>
                <input ref="bread-slice"/>
            </inputs>
            <tools>
                <tool ref="knife" reusable="true"/>
            </tools>
            <outputs>
                <output id="buttered-slice">buttered bread slice</output>
            </outputs>
        </task>
        <task operation="slice">
            <options>
                <option name="parts">
                    <numeric-value number="6"/>
                </option>
            </options>
            <inputs>
                <input ref="cucumber"/>
            </inputs>
            <tools>
                <tool ref="knife" reusable="true"/>
            </tools>
            <outputs>
                <output id="cucumber-slices">cucumber slices</output>
            </outputs>
        </task>
        <task operation="slice">
            <options>
                <option name="parts">
                    <numeric-value number="10"/>
                </option>
            </options>
            <inputs>
                <input ref="tomato"/>
            </inputs>
            <tools>
                <tool ref="knife" reusable="true"/>
            </tools>
            <outputs>
                <output id="tomato-slices">tomato slices</output>
            </outputs>
        </task>
        <task operation="place">
            <instructions>
                Place the
                <input ref="buttered-slice"/>
                on the
                <tool ref="plate"/>
            </instructions>
            <outputs>
                <output id="sandwich-base">sandwich base</output>
            </outputs>
        </task>
        <task operation="add-on-top">
            <inputs>
                <input ref="sandwich-base"/>
                <input ref="cucumber-slices"/>
            </inputs>
            <outputs>
                <output id="sandwich-with-cucumber">sandwich with cucumber</output>
            </outputs>
        </task>
        <task operation="add-on-top">
            <inputs>
                <input ref="sandwich-with-cucumber"/>
                <input ref="tomato-slices"/>
            </inputs>
            <outputs>
                <output id="sandwich-with-tomato">butter sandwich with cucumber and tomato</output>
            </outputs>
        </task>
        <task operation="stack">
            <inputs>
                <input ref="sandwich-with-tomato"/>
                <input ref="bread-slice"/>
            </inputs>
            <outputs>
                <output id="sandwich">sandwich with cucumber and tomato</output>
            </outputs>
        </task>
    </tasks>
</recipe>
