=== gadgetmies/flow-recipe/packages/server/src/recipes/recipe.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    
    <!-- Root element: recipe -->
    <xs:element name="recipe">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="title" type="xs:string"/>
                <xs:element name="ingredients">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ingredient" maxOccurs="unbounded">
                                <xs:complexType mixed="true">
                                    <xs:sequence>
                                        <xs:element name="properties" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="property" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:choice>
                                                                <xs:element name="numeric-value" type="numeric-value-type"/>
                                                                <xs:element name="text-content" type="xs:string" minOccurs="0"/>
                                                            </xs:choice>
                                                            <xs:attribute name="name" type="xs:string" use="required"/>
                                                            <xs:attribute name="value" type="xs:string"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="tools">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="tool" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType mixed="true">
                                    <xs:sequence>
                                        <xs:element name="properties" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="property" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:choice>
                                                                <xs:element name="numeric-value" type="numeric-value-type"/>
                                                                <xs:element name="text-content" type="xs:string" minOccurs="0"/>
                                                            </xs:choice>
                                                            <xs:attribute name="name" type="xs:string" use="required"/>
                                                            <xs:attribute name="value" type="xs:string"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="tasks">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="task" maxOccurs="unbounded">
                                <xs:complexType mixed="true">
                                    <xs:choice maxOccurs="unbounded">
                                        <xs:element name="input">
                                            <xs:complexType mixed="true">
                                                <xs:attribute name="ref" type="xs:string" use="required"/>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="tool">
                                            <xs:complexType mixed="true">
                                                <xs:attribute name="ref" type="xs:string" use="required"/>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="output">
                                            <xs:complexType mixed="true">
                                                <xs:attribute name="id" type="xs:string" use="required"/>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="options">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="option" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:choice>
                                                                <xs:element name="numeric-value" type="numeric-value-type"/>
                                                                <xs:element name="text-content" type="xs:string" minOccurs="0"/>
                                                            </xs:choice>
                                                            <xs:attribute name="name" type="xs:string" use="required"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="tools">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="tool" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:attribute name="ref" type="xs:string" use="required"/>
                                                            <xs:attribute name="reserved" type="xs:boolean"/>
                                                            <xs:attribute name="name" type="xs:string"/>
                                                            <xs:attribute name="reusable" type="xs:boolean"/>
                                                            <xs:attribute name="amount" type="xs:decimal" default="1"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="inputs">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="input" maxOccurs="unbounded">
                                                        <xs:complexType mixed="true">
                                                            <xs:attribute name="ref" type="xs:string" use="required"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="outputs">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:choice maxOccurs="unbounded">
                                                        <xs:element name="output">
                                                            <xs:complexType>
                                                                <xs:simpleContent>
                                                                    <xs:extension base="xs:string">
                                                                        <xs:attribute name="id" type="xs:string" use="required"/>
                                                                    </xs:extension>
                                                                </xs:simpleContent>
                                                            </xs:complexType>
                                                        </xs:element>
                                                        <xs:element name="tool">
                                                            <xs:complexType>
                                                                <xs:attribute name="ref" type="xs:string" use="required"/>
                                                                <xs:attribute name="name" type="xs:string"/>
                                                                <xs:attribute name="reusable" type="xs:boolean"/>
                                                                <xs:attribute name="amount" type="xs:decimal" default="1"/>
                                                            </xs:complexType>
                                                        </xs:element>
                                                    </xs:choice>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="instructions">
                                            <xs:complexType mixed="true">
                                                <xs:choice maxOccurs="unbounded">
                                                    <xs:element name="input">
                                                        <xs:complexType mixed="true">
                                                            <xs:attribute name="ref" type="xs:string" use="required"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="tool">
                                                        <xs:complexType mixed="true">
                                                            <xs:attribute name="ref" type="xs:string" use="required"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="output">
                                                        <xs:complexType mixed="true">
                                                            <xs:attribute name="id" type="xs:string" use="required"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="option">
                                                        <xs:complexType>
                                                            <xs:choice>
                                                                <xs:element name="numeric-value" type="numeric-value-type"/>
                                                                <xs:element name="text-content" type="xs:string" minOccurs="0"/>
                                                            </xs:choice>
                                                            <xs:attribute name="name" type="xs:string" use="required"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:choice>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:choice>
                                    <xs:attribute name="operation" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="ref" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    
    <!-- Numeric value type -->
    <xs:complexType name="numeric-value-type">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="number" type="xs:decimal" use="required"/>
                <xs:attribute name="unit" type="xs:string"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    
</xs:schema>

=== gadgetmies/flow-recipe/packages/server/src/recipes/debug-cake.xml
<?xml version="1.0" encoding="utf-8" ?>
<recipe ref="https://www.wearesovegan.com/epic-microwave-chocolate-cake/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="recipe.xsd">
    <title>Epic Microwave Chocolate Cake</title>
    <ingredients>
        <ingredient id="soya-milk">soya milk</ingredient>
        <ingredient id="dark-chocolate">dark chocolate</ingredient>
    </ingredients>
    <tools>
        <tool id="silicone-cake-mould">silicone cake mould<properties>
                <property name="circumference">
                    <numeric-value number="20" unit="centimeters"/>
                </property>
            </properties>
        </tool>
        <tool id="microwave-safe-jug">microwave safe jug</tool>
        <tool id="spatula">spatula</tool>
        <tool id="bowl">bowl</tool>
        <tool id="parchment-paper">parchment paper</tool>
        <tool id="frosting-spatula">frosting spatula</tool>
        <tool id="grater">grater</tool>
        <tool id="cooling-rack">cooling rack</tool>
        <tool id="fridge">fridge</tool>
        <tool id="precision-scale">precision scale</tool>
        <tool id="kitchen-scale">kitchen scale</tool>
        <tool id="plate">plate</tool>
    </tools>
    <tasks>
        <task operation="measure">
            <options>
                <option name="amount">
                    <numeric-value number="300" unit="ml"/>
                </option>
            </options>
            <tools>
                <tool ref="kitchen-scale"/>
            </tools>
            <inputs>
                <input ref="soya-milk"/>
            </inputs>
            <outputs>
                <output id="measured-soya-milk">soya milk</output>
            </outputs>
        </task>
        <task operation="measure">
            <options>
                <option name="amount">
                    <numeric-value number="100" unit="g"/>
                </option>
            </options>
            <tools>
                <tool ref="kitchen-scale"/>
            </tools>
            <inputs>
                <input ref="dark-chocolate"/>
            </inputs>
            <outputs>
                <output id="dark-chocolate-for-base">dark chocolate for base</output>
            </outputs>
        </task>
        <task operation="mix">
            <instructions>
                Combine the
                <input ref="measured-soya-milk"/>
                and
                <input ref="dark-chocolate-for-base"/>
                in a
                <tool ref="bowl" reserved="true"/>.
                Set to side so it turns into
                <output id="dough">vegan buttermilk</output> <!-- TODO: is a spatula needed? -->
            </instructions>
        </task>
        <task operation="split">
            <options>
                <option name="parts">
                    <numeric-value number="2"/>
                </option>
            </options>
            <inputs>
                <input ref="dough"/>
            </inputs>
            <tools>
                <tool ref="bowl" reserved="true"/>
            </tools>
            <outputs>
                <output id="split-dough-in-a-bowl">split dough</output>
            </outputs>
        </task>
        <task operation="pour">
            <instructions>
                Pour the
                <input ref="split-dough-in-a-bowl"/>
                into the mould
            </instructions>
            <outputs>
                <output id="dough-in-mould">dough in the mould</output>
                <tool ref="bowl" name="used bowl"/>
            </outputs>
        </task>
        <task operation="bake-in-microwave"> <!-- operation is identical to heat -->
            <instructions>
                Bake the
                <input ref="dough-in-mould"/>
                in the
                <tool ref="microwave"/>
                for
                <option name="duration">
                    <numeric-value number="6" unit="minutes"/>
                </option>
                or until a toothpick comes out clean.
            </instructions>
            <outputs>
                <output id="baked-cake">baked cake</output>
            </outputs>
        </task>
        <task operation="fill">
            <instructions>
                Place a
                <input ref="baked-cake">the cake and rack</input>
                on top of a <!-- TODO: need for a way to reference specific parts of a split? -->
                <tool ref="tray"/>
                to collect the ganache glaze which will run down the sides of the cake.
                Spread the foo
                over the top of the cake and place a second
                <input ref="baked-cake">cake</input>
                on top. Make sure the cake remains on top of a cooling rack.
            </instructions>
            <outputs>
                <output id="filled-cake">filled cake</output>
                <tool ref="spatula"/>
            </outputs>
        </task>
    </tasks>
</recipe>

=== gadgetmies/flow-recipe/packages/server/src/recipes/negroni.xml
<?xml version="1.0" encoding="utf-8" ?>
<recipe xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="recipe.xsd" ref="https://www.tentoonerum.com/cocktails/negroni/">
    <title>Rum Negroni</title>
    <ingredients>
        <ingredient id="rum">white or dark rum</ingredient>
        <ingredient id="campari">Campari</ingredient>
        <ingredient id="sweet-vermouth">sweet Vermouth</ingredient>
        <ingredient id="orange-bitters">orange bitters</ingredient>
        <ingredient id="ice-cubes">ice cubes</ingredient>
        <ingredient id="orange-peel">orange peel</ingredient>
        <ingredient id="large-ice-cube">large ice cube</ingredient>
    </ingredients>
    <tools>
        <tool id="mixing-glass">mixing glass</tool>
        <tool id="bar-spoon">bar spoon</tool>
        <tool id="strainer">strainer</tool>
        <tool id="rocks-glass">rocks glass</tool>
    </tools>
    <tasks>
        <task operation="fill">
            <instructions>
                Fill the
                <tool ref="mixing-glass"/>
                with
                <input ref="ice-cubes"/>
            </instructions>
            <outputs>
                <output id="filled-mixing-glass">mixing glass with ice</output>
            </outputs>
        </task>
        <task operation="measure">
            <options>
                <option name="amount">
                    <numeric-value number="1" unit="oz"/>
                </option>
            </options>
            <inputs>
                <input ref="rum"/>
                <input ref="filled-mixing-glass"/>
            </inputs>
            <outputs>
                <output id="measured-rum">rum in mixing glass</output>
            </outputs>
        </task>
        <task operation="measure">
            <options>
                <option name="amount">
                    <numeric-value number="1" unit="oz"/>
                </option>
            </options>
            <inputs>
                <input ref="campari"/>
                <input ref="measured-rum"/>
            </inputs>
            <outputs>
                <output id="measured-campari">ingredients in mixing glass</output>
            </outputs>
        </task>
        <task operation="measure">
            <options>
                <option name="amount">
                    <numeric-value number="1" unit="oz"/>
                </option>
            </options>
            <inputs>
                <input ref="sweet-vermouth"/>
                <input ref="measured-campari"/>
            </inputs>
            <outputs>
                <output id="measured-vermouth">ingredients in mixing glass</output>
            </outputs>
        </task>
        <task operation="measure">
            <options>
                <option name="amount">
                    <numeric-value number="2" unit="dashes"/>
                </option>
            </options>
            <inputs>
                <input ref="orange-bitters"/>
                <input ref="measured-vermouth"/>
            </inputs>
            <outputs>
                <output id="ingredients-in-mixing-glass">ingredients in mixing glass</output>
            </outputs>
        </task>
        <task operation="stir">
            <tools>
                <tool ref="bar-spoon" reserved="true"/>
            </tools>
            <inputs>
                <input ref="ingredients-in-mixing-glass"/>
            </inputs>
            <outputs>
                <output id="stirred-negroni">stirred negroni</output>
            </outputs>
        </task>
        <task operation="strain">
            <instructions>
                Strain
                <input ref="stirred-negroni"/>
                into
                <tool ref="rocks-glass"/>
                over
                <input ref="large-ice-cube"/>
                using a
                <tool ref="strainer"/>
            </instructions>
            <outputs>
                <output id="strained-negroni">negroni in glass</output>
            </outputs>
        </task>
        <task operation="express">
            <instructions>
                Express oils from
                <input ref="orange-peel"/>
                over
                <input ref="strained-negroni"/>
            </instructions>
            <outputs>
                <output id="expressed-negroni">negroni with expressed oils</output>
            </outputs>
        </task>
        <task operation="decorate">
            <instructions>
                Garnish
                <input ref="expressed-negroni"/>
                with
                <input ref="orange-peel"/>
            </instructions>
            <outputs>
                <output id="final-negroni">Rum Negroni</output>
            </outputs>
        </task>
    </tasks>
</recipe>
